### ISSUE TITLE
Terminal shows misaligned text output after pter is run

### ISSUE THREAD

**Issue by maxigaz** [vonshednob/pter#10]
After pter 2.2.0 is run, messages printed out by [khal](https://lostpackets.de/khal/) contain superfluous whitespace in Alacritty v0.9.0 and Zsh v5.8. So far, I could only fix it temporarily by starting a new shell session.

Here's a screencast showing the example of running `khal --help` before and after pter is run (with an empty todo file):

https://user-images.githubusercontent.com/10419911/141444265-67a9de1c-ce9d-4349-8dc4-af74bc164b10.mp4

Edit: Any command using `cat` and `echo` is affected, too. For example:

- `echo $XDG_SESSION_TYPE`
- `cat /proc/cpuinfo`

**Comment by vonshednob** [comment]
That's a bad one. I'll look into it. Thanks for reporting it!

**Comment by vonshednob** [comment]
You’re running manjaro, right? So your alacritty should be around version 0.9.0?

**Comment by maxigaz** [comment]
Yes, it's still 0.9.0.

**Comment by vonshednob** [comment]
Looks like I never noticed that problem because I’m using `fish`. With `zsh` the problem was quite obvious though.

It’s fixed in the underlying `cursedspace` and thus also fixed in pter [version 2.2.1](https://github.com/vonshednob/pter/blob/master/CHANGELOG.md#221).

Thanks again for pointing it out! :grin:

**Comment by maxigaz** [comment]
I can confirm that it works now. Thank you!
